# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotional',
            field=models.BooleanField(default=False, verbose_name='Promocional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='promotional_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, verbose_name='Preço promocional'),
            preserve_default=False,
        ),
    ]
