# Generated by Django 2.0.dev20170222230156 on 2017-04-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
