# Generated by Django 2.0.dev20170222230156 on 2017-04-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20170421_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotionalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Preço promocional'),
            preserve_default=False,
        ),
    ]
