# Generated by Django 2.0.dev20170222230156 on 2017-04-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_product_promotionalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotionalPrice',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
    ]
