# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20170525_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotional_price',
        ),
    ]
