# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_product_promotional_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
