# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20170521_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartManager',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'PayPal')], default='deposit', max_length=20, verbose_name='Opção de pagamento'),
        ),
    ]
