# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20170525_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens dos Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item do pedido', 'verbose_name_plural': 'Itens dos pedidos'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Chave do Carrinho'),
        ),
    ]
